name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # Skip linting site-packages and virtual env, ignore F821/F824
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 \
          --statistics --exclude=zwivenv,__pycache__,.git \
          --ignore=F821,F824

    - name: Test with pytest
      run: |
        pip install pytest
        export PYTHONPATH=src
        pytest
